on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    permissions:
      contents: write  # to create release commit (google-github-actions/release-please-action)
      pull-requests: write  # to create release PR (google-github-actions/release-please-action)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - run: yarn install

      - uses: googleapis/release-please-action@v4.1.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - run: yarn build
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up QEMU
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ steps.release.outputs.release_created }}
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin  

      - name: Build and push Docker image for multiple platforms
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t unrealwombat/homepage:${{ steps.release.outputs.tag_name }} \
            -f deployments/Dockerfile \
            --push .
