on:
  pull_request:
    branches:
      - main

name: release-please-pr

env:
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  release-please-pr:
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - run: yarn install

      - name: Create version
        id: release
        run: |
          version=pre-$(echo ${{ github.event.number }} | tr -d '#')
          echo "version: $version"
          echo "tag_name=$version" >> "$GITHUB_OUTPUT"

      - run: yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/homepage:${{ steps.release.outputs.tag_name }}
          context: "."
          file: "deployments/Dockerfile"